#!/usr/bin/env bash

set -euo pipefail

# Edits the current collage/release in Rose.
node="$(readlink -f "$1")"

vpath="${node##/home/blissful/music}"

# Truncate the "$node" variable until the remaining "$1 virtual parts" remain.
trunc_node() {
    num_parts="$(echo "$vpath" | tr -cd '/' | wc -c)"
    realpath="$node"
    num_to_truncate=$((num_parts - $1))
    [[ num_to_truncate -lt 0 ]] && return
    for _ in $(seq 1 $num_to_truncate); do
        realpath="$(dirname "$realpath")"
    done
    echo "$realpath"
}

case "$vpath" in
    "/1. Releases"* | "/2. Releases"* | "/3. Releases"*)
        echo "node=$node"
        echo "vpath=$vpath"
        release="$(trunc_node 2)"
        echo "release=$release"
        [ "$release" ] && rose releases edit "$release"
        ;;
    "/4. Artists"* | "/5. Genres"* | "/6. Labels"*)
        release="$(trunc_node 3)"
        [ "$release" ] && rose releases edit "$release"
        ;;
    "/7. Collages"*)
        release="$(trunc_node 3)"
        if [ "$release" ]; then
            rose releases edit "$release"
        else
            collage="$(trunc_node 2)"
            [ "$collage" ] && rose collages edit "$(basename "$collage")"
        fi
        ;;
    "/8. Playlists"*)
        playlist="$(trunc_node 2)"
        [ "$playlist" ] && rose playlists edit "$(basename "$playlist")"
        ;;
esac
