#!/usr/bin/env bash

# Shuffle music/video files in a directory.

# Kill any existing instance of playmusic. This ensures we are only playing one
# thing simultaneously.
existing="$(ps x | grep 'playmusic-mpv' | grep -v grep | awk '{print $1}')"
if [ -n "$existing" ]; then
    echo "$existing" | xargs -n1 kill
fi

node="$(readlink -f "$1")"

# Plays a directory ($1) of music, optionally starting at file ($2).
playlist="$(fd . "$node" -e ogg -e opus -e mp3 -e m4a -e mkv -e ts | shuf)"
echo "$playlist" | \
    tr '\n' '\0' | \
    xargs -0 nohup mpv \
        --force-window \
        --title="playmusic-mpv" \
        --input-ipc-server="$XDG_RUNTIME_DIR/mpv-playmusic" \
        >/dev/null 2>&1 &

clear
