case $- in
    *i*) ;;
      *) return;;
esac

shopt -s checkwinsize
shopt -s no_empty_cmd_completion
shopt -s histappend
shopt -s globstar

HISTCONTROL=ignoreboth
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
HISTSIZE=10000
HISTFILESIZE=20000

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PS1="\[\e[96m\]\u\[\e[m\]@\[\e[96m\]\h\[\e[m\] \[\e[93m\]\w\[\e[m\] "

# Allows us to use aliases with sudo.
alias sudo='sudo '

alias grep='grep --color=auto'

alias ls='ls --color=auto --group-directories-first'
alias l='ls -lh'
alias la='ls -lah'

alias vim='nvim'
alias grep='grep --color=auto'
alias info='info --vi-keys'  # Emacs and cheese not allowed.

alias tn='tmux new -s'
alias ta='tmux attach -t'
alias tl='tmux ls'

alias rscp='rsync -ah --progress'

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
