set nocompatible
filetype plugin indent on
syntax on

" Graphical stuff.
set background=dark
set hlsearch

" Line numbers
set number
set relativenumber

" Wrapping/indentation.
set whichwrap=b,s,<,>,[,]
set autoindent

" Options to make CoC work well.
set hidden
set nobackup
set nowritebackup

" Extra space to display messages.
set cmdheight=2

" Turn off error bells
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" More powerful backspacing
set backspace=indent,eol,start

" Bash & emacs-style completion for file selection
set wildmode=longest,list
set wildmenu

" Auto-reload files modified outside of vim.
set autoread

" Automatic comment continuation.
set formatoptions+=r

" We don't want double spaces after punctuation since we are not a boomer.
set nojoinspaces

" Ignore case on all-lowercase searches, check case otherwise.
set ignorecase
set smartcase

" Set leader keys
nnoremap <Space> <nop>
let mapleader = " "
let maplocalleader = "\\"

" I keep hitting <F1> on my bigger keyboard instead of <Esc>...
map <F1> <Esc>
imap <F1> <Esc>

" File indent settings.

set expandtab
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set formatoptions+=t

au BufEnter *.txt,*.py,*.rst,*.c,*.md,*.mkd,*.markdown,*.tex
  \ set textwidth=79

au BufEnter *.py,*.hs,*.ts,*.tsx,*.js,*.jsx
  \ set textwidth=88

au BufEnter *.md,*.js,*.yml,*.html,*.css,*.json,*.tex,*.vue,*.ex,*.exs,*.scss,*.rb,*.ml,*.jsx,*.ts,*.tsx,*.vim,*.hbs,*.rkt,*.hs
  \ set tabstop=2 |
  \ set softtabstop=2 |
  \ set shiftwidth=2

" For certain C++ codebases.
" au BufEnter *.cpp,*.h
"   \ set tabstop=2 |
"   \ set softtabstop=2 |
"   \ set shiftwidth=2

au BufEnter Makefile,makefile,*.php
  \ set noexpandtab

au BufEnter *.md,*.mkd,*.markdown,*.rst,*.tex,*.txt
  \ set spell

" Don't spell-check capitalization.
set spellcapcheck=

" Trailing space highlighting
highlight ExtraWhitespace ctermbg=red guibg=red
au BufEnter * match ExtraWhitespace /\s\+$/

" Reopen file to last read line
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

" Key mappings.
nnoremap <Leader>n :noh<CR>

nnoremap <Leader>s :split<CR><C-W>j
nnoremap <Leader>v :vsplit<CR><C-W>l

nnoremap <Leader>o :silent %w !wl-copy<CR>

nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

nnoremap - :silent bprevious<CR>
nnoremap = :silent bnext<CR>
nnoremap <Backspace> :silent b#<CR>
nnoremap <Leader><Backspace> :silent bp<bar>sp<bar>bn<bar>bd<CR>

nnoremap <Leader>r- :resize -10<CR>
nnoremap <Leader>r= :resize +10<CR>
nnoremap <Leader>r, :vertical resize -10<CR>
nnoremap <Leader>r. :vertical resize +10<CR>

nnoremap <Leader>e- :cprevious<CR>
nnoremap <Leader>e= :cnext<CR>
nnoremap <Leader>e, :lprevious<CR>
nnoremap <Leader>e. :lnext<CR>
