[tool.ruff]
line-length = 180
exclude = [".venv", ".*_cache", ".tach", "**/__codegen*__", "claude", "./tools/codegen_db_plugin/proto.py"]
target-version = "py313"
preview = true

[tool.ruff.lint]
# https://beta.ruff.rs/docs/configuration/
select = [
    "E",    # pycodestyle error
    "W",    # pycodestyle warning
    "F",    # pyflakes
    "I",    # isort
    "U",    # pyupgrade
    "B",    # bugbear
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "PIE",  # flake8-pie
    "RSE",  # flake8-raise
    "SLF",  # flake8-self
    "SLOT", # flake8-slots
    "TID",  # flake8-tidy-imports
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
    "RUF",  # ruff
    "INP",  # flake8-no-pep420
    "T20",  # flake8-print
    "PTH",  # flake8-use-pathlib
    # Individual rules.
    "PLC0415",  # https://docs.astral.sh/ruff/rules/import-outside-top-level/
]
ignore = [
    # Line too long; this happens with long strings etc. If it can't be autoformatted, nbd.
    "E501",
    # Undefined variables; handled by Pyright. Avoid doubling up.
    "F821",
    # ambiguous-unicode-character-string, many false positives.
    "RUF001",
    # Require async feature use within async functions; breaks on async route framework.
    "RUF029",
    # if-else-block-instead-of-if-exp, overcomplicated code.
    "SIM108",
]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
