set nocompatible
filetype plugin indent on
syntax on
set mouse=

" Miscellaneous
" -------------

" Dark!
set background=dark

" Live previews for search/substitute
set hlsearch
if has('nvim')
  set inccommand=nosplit
end

" Line numbers
set number
set relativenumber

" Wrapping/indentation.
set whichwrap=b,s,<,>,[,]
set autoindent

" Options to make CoC work well.
set hidden
set nobackup
set nowritebackup

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=50

" Extra space to display messages.
set cmdheight=2

" Turn off error bells
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" More powerful backspacing
set backspace=indent,eol,start

" Bash & emacs-style completion for file selection
set wildmode=longest,list
set wildmenu

" Auto-reload files modified outside of vim.
set autoread

" Automatic comment continuation.
set formatoptions+=r

" We don't want double spaces after punctuation since we are not a boomer.
set nojoinspaces

" Ignore case on all-lowercase searches, check case otherwise.
set ignorecase
set smartcase

" Reopen file to last read line
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Filetype settings
" -----------------

" Custom overrides
au BufReadPost,BufNewFile *.rkt set filetype=racket
au filetype racket set lisp
au BufReadPost,BufNewFile *.sqlx set filetype=sql

" Default indentation settings
set expandtab
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set formatoptions+=t

" Per-filetype indentation settings
au BufEnter *.py set textwidth=100 | set formatoptions-=t
au BufEnter *.js,*.jsx,*.ts,*.tsx set textwidth=100 | set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.c,*.h set textwidth=79
" au BufEnter *.cpp,*.h set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.html set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.css,*.scss set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.yml,*.yaml set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.json set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter Makefile,makefile set noexpandtab
au BufEnter *.hs set textwidth=100 | set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.lua set tabstop=2 | set softtabstop=2 | set shiftwidth=2 | set noexpandtab
au BufEnter *.vue set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.ex,*.exs set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.rb set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.ml set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.vim set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.hbs set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.rkt set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.v set textwidth=100 | set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.php set noexpandtab

au BufEnter *.txt set textwidth=100
au BufEnter *.md,*.mkd,*.markdown set textwidth=100 | set tabstop=2 | set softtabstop=2 | set shiftwidth=2
au BufEnter *.rst set textwidth=100
au BufEnter *.tex set textwidth=100 | set tabstop=2 | set softtabstop=2 | set shiftwidth=2

" NVM, turn spell off.
" au BufEnter *.md,*.mkd,*.markdown,*.rst,*.tex,*.txt set spell | set spellcapcheck=

" Key mappings
" ------------

" Set leader keys
nnoremap <Space> <nop>
let mapleader = " "
let maplocalleader = "\\"

nnoremap <Leader>n <Cmd>noh<CR>

nnoremap <Leader>s <Cmd>split<CR><C-W>j
nnoremap <Leader>v <Cmd>vsplit<CR><C-W>l

nnoremap <Leader>o :silent %w !wl-copy<CR>

nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

nnoremap - :silent bprevious<CR>
nnoremap = :silent bnext<CR>
nnoremap <Backspace> :silent b#<CR>
nnoremap <Leader><Backspace> :silent bp<bar>silent sp<bar>silent bn<bar>silent bd<CR>

nnoremap <Leader>r- <Cmd>resize -10<CR>
nnoremap <Leader>r= <Cmd>resize +10<CR>
nnoremap <Leader>r, <Cmd>vertical resize -10<CR>
nnoremap <Leader>r. <Cmd>vertical resize +10<CR>

nnoremap M <Cmd>cprevious<CR>
nnoremap m <Cmd>cnext<CR>

" <C-r> in visual mode to S&R selected text.
vnoremap <C-r> "hy:%s/<C-r>h//g<left><left>

" Bind <C-w> to automatically correct the previous word in insert & normal mode.
inoremap <C-w> <c-g>u<Esc>[s1z=`]a<c-g>u
nnoremap <C-w> i<c-g>u<Esc>[s1z=`]a<c-g>u<Esc>

" Create parent directories when saving new files.
au BufWritePre,FileWritePre * silent! call mkdir(expand('<afile>:p:h'), 'p')

" Auto-exit when editing some filetypes. Do not allow them to be edited
au BufEnter *.ogg,*.opus,*.m4a,*.mp4,*.mkv,*.mp3,*.jpg,*.jpeg,*.png,*.webm,*.gif,*.cbz,*.cbr,*.pdf :bd
