version: '3.3'
networks:
  internal:
    external: false
volumes:
  certificates:
  komga-config:
  saffron-data:
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - certificates:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - saffron
  certbot:
    image: certbot/certbot:latest
    restart: never
    command: certonly --manual --preferred-challenges=dns --agree-tos -d sunsetglow.net -d *.sunsetglow.net
    volumes:
      - certificates:/etc/letsencrypt:rw
  saffron:
    image: blissful/saffron
    command: start -h 0.0.0.0
    restart: always
    volumes:
      - saffron-data:/appdata:rw
    networks:
      - internal
    ports:
      - "100.71.28.44:7071:8000"
    environment:
      - HOST_URL=https://u.sunsetglow.net
